services:
  # The Backend Service (Python/Flask App)
  # This service runs your Python logic.
  - type: web
    name: shonfxkenya-backend
    env: python
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    # THIS IS THE MOST IMPORTANT LINE TO FIX THE PAYMENT ISSUE
    plan: free 
    healthCheckPath: /
    envVars:
      - key: DERIV_API_TOKEN
        sync: false # Set this secret in the Render dashboard

  # The Frontend Service (React Static Site)
  # This service is already on the free plan by default.
  - type: web
    name: shonfxkenya-frontend
    env: static
    plan: free # Good practice to be explicit here too
    buildFilter:
      paths:
      - frontend/**
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /api/:path*
        destination: http://shonfxkenya-backend/:path*
      - type: rewrite
        source: /*
        destination: /index.html
