services:
  # The Backend Service (Python/Flask App)
  # This service needs 'plan: free' to avoid payment requests.
  - type: web
    name: shonfxkenya-backend
    env: python
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free # This is CORRECT and NECESSARY for the backend.
    healthCheckPath: /
    envVars:
      - key: DERIV_API_TOKEN
        sync: false # Set this secret in the Render dashboard

  # The Frontend Service (React Static Site)
  # This service is free by default and MUST NOT have the 'plan' line.
  - type: web
    name: shonfxkenya-frontend
    env: static
    # The 'plan: free' line has been REMOVED from here because it's invalid.
    buildFilter:
      paths:
      - frontend/**
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /api/:path*
        destination: http://shonfxkenya-backend/:path*
      - type: rewrite
        source: /*
        destination: /index.html
