services:
  # The Backend Service (Python/Flask App)
  - type: web
    name: shonfxkenya-backend
    env: python
    runtime: docker
    # THIS IS THE CRUCIAL FIX:
    # It tells Render to use the 'backend' folder as the context for the build.
    dockerContext: ./backend
    dockerfilePath: ./Dockerfile # The path is now relative to the context
    plan: free
    healthCheckPath: /
    envVars:
      - key: DERIV_API_TOKEN
        sync: false # Set this secret in the Render dashboard

  # The Frontend Service (React Static Site)
  - type: web
    name: shonfxkenya-frontend
    env: static
    buildFilter:
      paths:
      - frontend/**
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /api/:path*
        destination: http://shonfxkenya-backend/:path*
      - type: rewrite
        source: /*
        destination: /index.html
